### Необходимые библиотеки

In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Метод подбора
y = 0.4*x + 3 + noise

In [3]:
from ipywidgets import interactive
a = np.linspace(-5,5,50)
noise = np.random.uniform(-5,5, size=(50,))
d = .4 * a + 3 + noise

def f(m, b):
    plt.figure(2)
    x = np.linspace(-10, 10, num=1000)
    plt.scatter(a,d)
    plt.plot(x, m * x + b, color='red')
    plt.ylim(-3, 5)
    plt.show()

interactive_plot = interactive(f, m=(-2.0, 2.0), b=(-3, 3, 0.5))
output = interactive_plot.children[-1]
output.layout.height = '400px'
interactive_plot

interactive(children=(FloatSlider(value=0.0, description='m', max=2.0, min=-2.0), FloatSlider(value=0.0, descr…

In [ ]:
### f(x) = 0.9 * x + 2

In [4]:
0.9 * 2.5 + 2

4.25

In [6]:
0.4 * 2.5 + 3 + np.random.uniform()

4.440407890049551

In [7]:
0.9 * (-7.5) + 2

-4.75

In [8]:
0.4 * (-7.5) + 3 + np.random.uniform()

0.669186315849769

### Функция создания таргета: <i><font color='red'>y = x_1 * 2 + x_2 + random_noise</font></i>

## Расчет beta коэффициентов с помощью матричной математики. Расчет потерь - метод наименьших квадратов

#### Dataset

In [9]:
X_1 = np.linspace(1,30, 150)
X_2 = X_1 + 10
Y = X_1 * 2  + X_2 + np.random.rand()

In [10]:
df = pd.DataFrame({'X_1': X_1, 'X_2': X_2, 'Y': Y})
df.head()

X_1        X_2          Y
0  1.000000  11.000000  13.496224
1  1.194631  11.194631  14.080116
2  1.389262  11.389262  14.664009
3  1.583893  11.583893  15.247901
4  1.778523  11.778523  15.831794

#### Beta coeffs: <i><font color='red'> np.dot((np.linalg.inv(np.dot(X.T,X))), np.dot(X.T,Y)) </font></i>

In [11]:
X = df.drop('Y', axis=1)
Y = df['Y']

In [28]:
weights = np.dot((np.linalg.inv(np.dot(X.T,X))), np.dot(X.T,Y))

### Немного линейной алгебры

In [13]:
a = np.array([[1,2,3],[4,5,6]])

In [21]:
a.shape

(2, 3)

In [19]:
b = np.array([[1,1,1]])

In [20]:
b.shape

(1, 3)

In [23]:
b @ a

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [24]:
a @ b.T

array([[ 6],
       [15]])

### Продолжение

In [29]:
weights

array([1.95037764, 1.04962236])

In [33]:
df.tail(3)

X_1        X_2           Y         Y_1
147  29.610738  39.610738   99.328438   99.328438
148  29.805369  39.805369   99.912331   99.912331
149  30.000000  40.000000  100.496224  100.496224

In [31]:
df['Y_1'] = df['X_1'] * weights[0] + df['X_2'] * weights[1]

In [34]:
df['Y_1'].mean()

56.99622357037881

In [35]:
df['Y'].mean()

56.99622357037877

In [36]:
df.tail(3)

X_1        X_2           Y         Y_1
147  29.610738  39.610738   99.328438   99.328438
148  29.805369  39.805369   99.912331   99.912331
149  30.000000  40.000000  100.496224  100.496224

In [37]:
31 * weights[0] + 41 * weights[1]

103.49622357037873

In [38]:
X_3 = np.linspace(31,51,30)
X_4 = X_3 + 10

In [39]:
Y_2 = X_3 * weights[0] + X_4 * weights[1]

In [40]:
df_1 = pd.DataFrame({'X_3': X_3, 'X_4': X_4, 'Y_2': Y_2})

In [43]:
df_1.head()

X_3        X_4         Y_2           Y
0  31.000000  41.000000  103.496224  103.607969
1  31.689655  41.689655  105.565189  105.676935
2  32.379310  42.379310  107.634155  107.745900
3  33.068966  43.068966  109.703120  109.814866
4  33.758621  43.758621  111.772086  111.883831

In [42]:
df_1['Y'] = df_1['X_3'] * 2 + df_1['X_4'] + np.random.rand()

In [44]:
df_1['Y_2'].mean() / df_1['Y'].mean()

0.9991636320187577

### Так зачем все это

In [45]:
X_1 = np.linspace(1,30, 150)
X_2 = X_1 + 10
Y = X_1 ** 3  - np.exp(np.cos(X_2)) + np.random.rand()
df = pd.DataFrame({'X_1': X_1, 'X_2': X_2, 'Y': Y})
df.head()

X_1        X_2         Y
0  1.000000  11.000000  0.971761
1  1.194631  11.194631  1.462454
2  1.389262  11.389262  2.189985
3  1.583893  11.583893  3.207856
4  1.778523  11.778523  4.577324

In [46]:
df.tail()

X_1        X_2             Y
145  29.221477  39.221477  24951.990202
146  29.416107  39.416107  25454.086380
147  29.610738  39.610738  25962.831865
148  29.805369  39.805369  26478.274421
149  30.000000  40.000000  27000.462918

In [47]:
X = df.drop('Y',axis=1)
Y = df['Y']

In [48]:
weights = np.dot((np.linalg.inv(np.dot(X.T,X))), np.dot(X.T,Y))

In [49]:
30 * weights[0] + 40 * weights[1]

19330.68714825723

In [50]:
weights

array([1461.28796942, -612.69879836])